### ISSUE TITLE
artworkUrl100が取得できない問題について

### ISSUE THREAD

**Issue by hondamarlboro** [connect1ngdots/AppHtml#39]
2015年11月6日頃より、iTunes Search APIからアプリ（entityがsoftware、iPadSoftware、macSoftware）のartworkUrl100の値が返されない状態が続いております。

〈AppHtmlへの影響〉
予約語${icon100url}に該当する値が返されない場合、後続処理への影響遮断の観点から検索結果より除外するようにしています。このためブックマークレット、AppHtmlWebでアプリを検索しても何も反応しない（プログラムとしては正常に終了）状態となっております。

〈当面の暫定的措置〉
Search APIの仕様変更かどうかを見極める必要があるため、AppHtmlについては以下のように最小限の修正にとどめます。

・artworkUrl100が返されないことによる検索結果からの除外対応をはずします。
・artworkUrl100が返されない場合、${icon100url}にはartworkUrl512に差し替え、当該URLも返されない場合にはartworkUrl60を自動的に適用します。

〈抜本的な対応〉
度々発生するSearch APIの仕様変更または不具合等に柔軟に対処する後方互換に向けた取り組みは別途検討を進めて参ります。

**Comment by feelingplace** [comment]
fix #40 #41
